permissions:
  contents: read
name: meta-qbee-pr-tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        arch: [x86_64,arm64]
        branch: [kirkstone,scarthgap]
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 600
    container:
      image: ghcr.io/siemens/kas/kas:4.8.1 # Use the latest kas container image
      options: --user 1000:1000
      env:
        KAS_CLONE_DEPTH: 0
        DL_DIR: /ci/yocto/downloads
        SSTATE_DIR: /ci/yocto/sstate
        TMPDIR: /ci/yocto/tmp
        # Environment variable for bootstrap key
        # This should be set in the GitHub repository secrets for security
        # when running integration tests with the platform
        QBEE_BOOTSTRAP_KEY: my-bootstrap-key
      volumes:
        - /home/runner/ci/yocto:/ci/yocto
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
      - name: Set up KAS
        run: |
           kas checkout kas/poky/qbee-agent.${{ matrix.branch }}.${{ matrix.arch }}.yml
      - name: Build with KAS
        run: |
          kas build kas/poky/qbee-agent.${{ matrix.branch }}.${{ matrix.arch }}.yml
  
  rauc-simple-build:
    needs: build
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 600
    container:
      image: ghcr.io/siemens/kas/kas:4.8.1 # Use the latest kas container image
      options: --user 1000:1000
      env:
        KAS_CLONE_DEPTH: 0
        DL_DIR: /ci/yocto/downloads
        SSTATE_DIR: /ci/yocto/sstate
        TMPDIR: /ci/yocto/tmp
      volumes:
        - /home/runner/ci/yocto:/ci/yocto
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 0
      
      - name: Set up KAS
        run: |
           kas checkout kas/poky/qbee-agent.scarthgap.rauc-simple.yml
      
      - name: Build with KAS
        run: |
          kas build kas/poky/qbee-agent.scarthgap.rauc-simple.yml
  build-demo-docker:

    needs: rauc-simple-build
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 600
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 0
          
      - name: Build Docker
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/meta-container-os/docker/images
          
          cp /home/runner/ci/yocto/tmp/deploy/images/qemux86-64/ovmf.qcow2 \
            ${GITHUB_WORKSPACE}/meta-container-os/docker/images/

          cp /home/runner/ci/yocto/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64.rootfs.wic \
            ${GITHUB_WORKSPACE}/meta-container-os/docker/images/vmimage.wic

          cd ${GITHUB_WORKSPACE}/meta-container-os/docker
          
          docker build -t qbeeio/qbee-demo:rauc-latest .